### ISSUE TITLE
Clear relations problem on update

### ISSUE THREAD

**Issue by odlex** [BRACKETS-by-TRIAD/admin-generator#21]
There is a problem when I want to clear the roles relationship UserController::update(), I think you should rather test with the function Request::has ()

Exemple:
```
if($request->has('roles')) {
      $user->roles()->sync(collect($request->input('roles', []))->map->id->toArray());
 }
```

https://github.com/BRACKETS-by-TRIAD/admin-generator/blob/78f7194024dcd652d56e4e340184b79eee8c476a/resources/views/controller.blade.php#L164

**Comment by palypster** [comment]
Valid point, thanks. Feel free to file a pull request for that ;) I'd be glad to accept it.
